In [2]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv('messages.csv')
time = pd.read_csv('orders.csv')   # i haven't used this data

In [4]:
date.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with Dates

In [7]:
# Converting to datetime datatype

date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

### 1. Extract Year

In [9]:
date['date_year'] = date['date'].dt.year

date.head()

,date,msg,date_year
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013

### 2. Extract Month

In [11]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,msg,date_year,date_month_name
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,December
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,April
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,December
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,November
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,October

In [13]:
date['date_month_name'] = date['date'].dt.month

date.head()

,date,msg,date_year,date_month_name
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10

### Extract Days

In [15]:
date['date_day'] = date['date'].dt.day

date.head()

,date,msg,date_year,date_month_name,date_day
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26

In [17]:
# Day Of Week

date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,msg,date_year,date_month_name,date_day,date_dow
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15,6
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29,1
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30,6
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28,4
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26,5

In [21]:
# day of week name 

date['date_dow_name'] = date['date'].dt.day_name()

date.head()

,date,msg,date_year,date_month_name,date_day,date_dow,date_dow_name
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15,6,Sunday
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29,1,Tuesday
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30,6,Sunday
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28,4,Friday
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26,5,Saturday

In [23]:
# is weekend?

date['date_is_weekend']  =  np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']),1,0)

date.head()

,date,msg,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15,6,Sunday,1
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29,1,Tuesday,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30,6,Sunday,1
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28,4,Friday,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26,5,Saturday,1

### Extract week of year

In [25]:

date['date_week'] = date['date'].dt.week

date.head()

AttributeError: 'DatetimeProperties' object has no attribute 'week'

### Extract Quarter

In [26]:
date['quarter']  = date['date'].dt.quarter

date.head()

,date,msg,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15,6,Sunday,1,4
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29,1,Tuesday,0,2
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30,6,Sunday,1,4
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28,4,Friday,0,4
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26,5,Saturday,1,4

### Extract Semester

In [27]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)

date.head()

,date,msg,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,semester
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15,6,Sunday,1,4,2
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29,1,Tuesday,0,2,1
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30,6,Sunday,1,4,2
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28,4,Friday,0,4,2
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26,5,Saturday,1,4,2

### Extract Time elapsed between dates

In [30]:
import datetime

today = datetime.datetime.today()

today            # today's date

datetime.datetime(2026, 3, 14, 15, 6, 34, 102558)

In [31]:
today - date['date']

0     4472 days 14:16:34.102558
1     4336 days 15:26:34.102558
2     4822 days 14:45:34.102558
3     4124 days 14:35:34.102558
4     4521 days 15:55:34.102558
                 ...
995   5111 days 14:16:34.102558
996   4432 days 15:52:34.102558
997   4897 days 15:29:34.102558
998   5013 days 15:32:34.102558
999   4285 days 15:41:34.102558
Name: date, Length: 1000, dtype: timedelta64[ns]

In [33]:
(today - date['date']).dt.days

0      4472
1      4336
2      4822
3      4124
4      4521
       ...
995    5111
996    4432
997    4897
998    5013
999    4285
Name: date, Length: 1000, dtype: int64

In [39]:
## Minutes Passed


np.round((today - date['date'])  / np.timedelta64(1, 'm'), 0)

0      6440537.0
1      6244767.0
2      6944566.0
3      5939436.0
4      6511196.0
         ...
995    7360697.0
996    6383033.0
997    7052610.0
998    7219653.0
999    6171342.0
Name: date, Length: 1000, dtype: float64

In [41]:
time.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [42]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1000 non-null   datetime64[ns]
 1   msg              1000 non-null   object
 2   date_year        1000 non-null   int32
 3   date_month_name  1000 non-null   int32
 4   date_day         1000 non-null   int32
 5   date_dow         1000 non-null   int32
 6   date_dow_name    1000 non-null   object
 7   date_is_weekend  1000 non-null   int64
 8   quarter          1000 non-null   int32
 9   semester         1000 non-null   int64
dtypes: datetime64[ns](1), int32(5), int64(2), object(2)
memory usage: 58.7+ KB

In [45]:
date['hour']  = date['date'].dt.hour
date['min']  = date['date'].dt.hour
date['sec']  = date['date'].dt.hour

date.head()

,date,msg,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,semester,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15,6,Sunday,1,4,2,0,0,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29,1,Tuesday,0,2,1,23,23,23
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30,6,Sunday,1,4,2,0,0,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28,4,Friday,0,4,2,0,0,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26,5,Saturday,1,4,2,23,23,23

In [47]:
today - date['date']   # Time Difference

0     4472 days 14:16:34.102558
1     4336 days 15:26:34.102558
2     4822 days 14:45:34.102558
3     4124 days 14:35:34.102558
4     4521 days 15:55:34.102558
                 ...
995   5111 days 14:16:34.102558
996   4432 days 15:52:34.102558
997   4897 days 15:29:34.102558
998   5013 days 15:32:34.102558
999   4285 days 15:41:34.102558
Name: date, Length: 1000, dtype: timedelta64[ns]