In [25]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [26]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\sangr\anaconda3\lib\site-packages (4.13.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\sangr\anaconda3\lib\site-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sangr\anaconda3\lib\site-packages (from beautifulsoup4) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [27]:
requests.get('https://www.ambitionbox.com/list-of-companies?page=1')  ## it is finding our request as bot / robot req.

In [28]:
requests.get('https://www.ambitionbox.com/list-of-companies?page=1').text

'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;www&#46;ambitionbox&#46;com&#47;list&#45;of&#45;companies&#63;" on this server.<P>\nReference&#32;&#35;18&#46;c84bd217&#46;1765293799&#46;45dfba2d\n<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;c84bd217&#46;1765293799&#46;45dfba2d</P>\n</BODY>\n</HTML>\n'

In [29]:
## To Fetch HTML/ css code from website

headers = { 'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers).text

In [30]:
soup =  BeautifulSoup(webpage,'lxml')  # lxml is inbuilt function for HTML parser

In [65]:
# print(soup.prettify())   # webpage content

In [32]:
soup.find_all('h2')[0]

<h2 class="companyListing__title">
							Companies in India
						</h2>

In [33]:
soup.find_all('h2')[0].text

'\n\t\t\t\t\t\t\tCompanies in India\n\t\t\t\t\t\t'

In [34]:
len(soup.find_all('h2'))

21

In [35]:

for i in soup.find_all('h2'):
    print(i.text)

							Companies in India


									TCS


									Accenture


									Wipro


									Cognizant


									Capgemini


									HDFC Bank


									Infosys


									ICICI Bank


									HCLTech


									Tech Mahindra


									Genpact


									Teleperformance


									Axis Bank


									Jio


									Concentrix Corporation


									Amazon


									iEnergizer


									Reliance Retail


									IBM


									LTIMindtree

In [36]:

for i in soup.find_all('h2'):
    print(i.text.strip()) # strip -> to remove Gapps

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
ICICI Bank
HCLTech
Tech Mahindra
Genpact
Teleperformance
Axis Bank
Jio
Concentrix Corporation
Amazon
iEnergizer
Reliance Retail
IBM
LTIMindtree

In [66]:
# for i in soup.find_all('div'):
#     print(i.text.strip()) # all rating , review , Location

In [38]:
# so we have to find sepcific tag which is for ratting only

len(soup.find_all('div', class_='rating_text'))

20

In [39]:
soup.find_all('span',class_='companyCardWrapper__companyRatingCount')  ## get class of Ratings

[<span class="companyCardWrapper__companyRatingCount">
 								(1.1L)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(70k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(62.3k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(59.2k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(50.8k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(49.6k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(46.5k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(44.7k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(43.8k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(41.8k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(40.1k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(36k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(31.8k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(31.2k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(31.1k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(30.3k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(27.3k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(26.6k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(25.1k)
 							</span>,
 <span class="companyCardWrapper__companyRatingCount">
 								(24.8k)
 							</span>]

In [40]:
len(soup.find_all(class_='companyCardWrapper__companyRatingCount'))

20

In [41]:
##Taking Whole Container

In [42]:
company = soup.find_all('div', class_= 'companyCardWrapper')

In [43]:
len(company)

20

In [44]:


for i in company:
    print(i.find('h2'))

<h2 class="companyCardWrapper__companyName" title="TCS">
									TCS
								</h2>
<h2 class="companyCardWrapper__companyName" title="Accenture">
									Accenture
								</h2>
<h2 class="companyCardWrapper__companyName" title="Wipro">
									Wipro
								</h2>
<h2 class="companyCardWrapper__companyName" title="Cognizant">
									Cognizant
								</h2>
<h2 class="companyCardWrapper__companyName" title="Capgemini">
									Capgemini
								</h2>
<h2 class="companyCardWrapper__companyName" title="HDFC Bank">
									HDFC Bank
								</h2>
<h2 class="companyCardWrapper__companyName" title="Infosys">
									Infosys
								</h2>
<h2 class="companyCardWrapper__companyName" title="ICICI Bank">
									ICICI Bank
								</h2>
<h2 class="companyCardWrapper__companyName" title="HCLTech">
									HCLTech
								</h2>
<h2 class="companyCardWrapper__companyName" title="Tech Mahindra">
									Tech Mahindra
								</h2>
<h2 class="companyCardWrapper__companyName" title="Genpact">
									Genpact
								</h2>
<h2 class="companyCardWrapper__companyName" title="Teleperformance">
									Teleperformance
								</h2>
<h2 class="companyCardWrapper__companyName" title="Axis Bank">
									Axis Bank
								</h2>
<h2 class="companyCardWrapper__companyName" title="Jio">
									Jio
								</h2>
<h2 class="companyCardWrapper__companyName" title="Concentrix Corporation">
									Concentrix Corporation
								</h2>
<h2 class="companyCardWrapper__companyName" title="Amazon">
									Amazon
								</h2>
<h2 class="companyCardWrapper__companyName" title="iEnergizer">
									iEnergizer
								</h2>
<h2 class="companyCardWrapper__companyName" title="Reliance Retail">
									Reliance Retail
								</h2>
<h2 class="companyCardWrapper__companyName" title="IBM">
									IBM
								</h2>
<h2 class="companyCardWrapper__companyName" title="LTIMindtree">
									LTIMindtree
								</h2>

In [45]:


for i in company:
    print(i.find('h2').text.strip())

TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
ICICI Bank
HCLTech
Tech Mahindra
Genpact
Teleperformance
Axis Bank
Jio
Concentrix Corporation
Amazon
iEnergizer
Reliance Retail
IBM
LTIMindtree

In [64]:

names = []
rating = []
reviews = []
company_data = []


for i in company:
    names.append(i.find('h2').text.strip())
    reviews.append(i.find_all( class_ = 'companyCardWrapper__companyRatingCount')[0].text.strip())
    rating.append(i.find('div',class_ = 'rating_text').text.strip())
    company_data.append(i.find('span',class_ = 'companyCardWrapper__interLinking').text.strip())

    # OR

    ##rating.append(i.find( class_ = 'companyCardWrapper__companyRatingCount').text.strip())


    # find  --> for only 1 (we have only 1 h2 )
    # find_all --> when many attributes are present in class (rating, location,..)
    # [0] --> only 1 value is present 
    # .text.strip() --> to extract the data(rating/ name)


d = {'names': names, 'rating' :rating, 'reviews':reviews, 'company_data':company_data}
df = pd.DataFrame(d)
df

,names,rating,reviews,company_data
0,TCS,3.4,(1.1L),IT Services & Consulting | Bangalore / Bengalu...
1,Accenture,3.7,(70k),IT Services & Consulting | Bangalore / Bengalu...
2,Wipro,3.6,(62.3k),IT Services & Consulting | Hyderabad / Secunde...
3,Cognizant,3.7,(59.2k),IT Services & Consulting | Hyderabad / Secunde...
4,Capgemini,3.7,(50.8k),IT Services & Consulting | Bangalore / Bengalu...
5,HDFC Bank,3.8,(49.6k),Banking | Mumbai +1805 other locations
6,Infosys,3.5,(46.5k),IT Services & Consulting | Bangalore / Bengalu...
7,ICICI Bank,4.0,(44.7k),Banking | Mumbai +1433 other locations
8,HCLTech,3.4,(43.8k),IT Services & Consulting | Chennai +227 other ...
9,Tech Mahindra,3.4,(41.8k),IT Services & Consulting | Hyderabad / Secunde...
10,Genpact,3.6,(40.1k),IT Services & Consulting | Hyderabad / Secunde...
11,Teleperformance,3.8,(36k),BPO | Mumbai +252 other locations
12,Axis Bank,3.6,(31.8k),Banking | Mumbai +1490 other locations
13,Jio,4.3,(31.2k),Telecom | Mumbai +1851 other locations
14,Concentrix Corporation,3.6,(31.1k),BPO | Bangalore / Bengaluru +175 other locations
15,Amazon,3.9,(30.3k),Internet | Bangalore / Bengaluru +519 other lo...
16,iEnergizer,4.6,(27.3k),BPO | Noida +51 other locations
17,Reliance Retail,3.9,(26.6k),Retail | Mumbai +1140 other locations
18,IBM,3.9,(25.1k),IT Services & Consulting | Bangalore / Bengalu...
19,LTIMindtree,3.6,(24.8k),IT Services & Consulting | Bangalore / Bengalu...

In [52]:
names

['TCS',
 'Accenture',
 'Wipro',
 'Cognizant',
 'Capgemini',
 'HDFC Bank',
 'Infosys',
 'ICICI Bank',
 'HCLTech',
 'Tech Mahindra',
 'Genpact',
 'Teleperformance',
 'Axis Bank',
 'Jio',
 'Concentrix Corporation',
 'Amazon',
 'iEnergizer',
 'Reliance Retail',
 'IBM',
 'LTIMindtree']

In [53]:
rating

['3.4',
 '3.7',
 '3.6',
 '3.7',
 '3.7',
 '3.8',
 '3.5',
 '4.0',
 '3.4',
 '3.4',
 '3.6',
 '3.8',
 '3.6',
 '4.3',
 '3.6',
 '3.9',
 '4.6',
 '3.9',
 '3.9',
 '3.6']

In [54]:
 reviews

['(1.1L)',
 '(70k)',
 '(62.3k)',
 '(59.2k)',
 '(50.8k)',
 '(49.6k)',
 '(46.5k)',
 '(44.7k)',
 '(43.8k)',
 '(41.8k)',
 '(40.1k)',
 '(36k)',
 '(31.8k)',
 '(31.2k)',
 '(31.1k)',
 '(30.3k)',
 '(27.3k)',
 '(26.6k)',
 '(25.1k)',
 '(24.8k)']

In [57]:
company[0].find('span',class_ = 'companyCardWrapper__interLinking').text.strip()

'IT Services & Consulting | Bangalore / Bengaluru +436 other locations'

In [74]:
## to fetch data from differnt pages

final = pd.DataFrame()

for j in range(1,31):

    URL= 'https://www.ambitionbox.com/list-of-companies?page={}'.format(j)
    ## To Fetch HTML/ css code from website
    headers = { 'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
    webpage = requests.get(URL,headers=headers).text

    soup =  BeautifulSoup(webpage,'lxml') 

    company = soup.find_all('div', class_= 'companyCardWrapper')

    
    names = []
    rating = []
    reviews = []
    company_data = []
    
    
    for i in company:
        names.append(i.find('h2').text.strip())
        reviews.append(i.find_all( class_ = 'companyCardWrapper__companyRatingCount')[0].text.strip())
        rating.append(i.find('div',class_ = 'rating_text').text.strip())
        company_data.append(i.find('span',class_ = 'companyCardWrapper__interLinking').text.strip())
    
        # OR
    
        ##rating.append(i.find( class_ = 'companyCardWrapper__companyRatingCount').text.strip())
    
    
        # find  --> for only 1 (we have only 1 h2 )
        # find_all --> when many attributes are present in class (rating, location,..)
        # [0] --> only 1 value is present 
        # .text.strip() --> to extract the data(rating/ name)
    
    
    d = {'names': names, 'rating' :rating, 'reviews':reviews, 'company_data':company_data}
    df = pd.DataFrame(d)

    final = pd.concat([final, df], ignore_index=True)

In [75]:
final

,names,rating,reviews,company_data
0,TCS,3.4,(1.1L),IT Services & Consulting | Bangalore / Bengalu...
1,Accenture,3.7,(70k),IT Services & Consulting | Bangalore / Bengalu...
2,Wipro,3.6,(62.3k),IT Services & Consulting | Hyderabad / Secunde...
3,Cognizant,3.7,(59.2k),IT Services & Consulting | Hyderabad / Secunde...
4,Capgemini,3.7,(50.8k),IT Services & Consulting | Bangalore / Bengalu...
...,...,...,...,...
595,LivSpace,3.4,(1.6k),Architecture & Interior Design | Bangalore / B...
596,Granules India Limited,3.8,(1.6k),Pharma | Hyderabad / Secunderabad +21 other lo...
597,Tata Play,4.0,(1.6k),Broadcasting | Mumbai +220 other locations
598,TTEC India,3.7,(1.6k),BPO | Ahmedabad +34 other locations
599,Caterpillar Inc,4.1,(1.6k),Industrial Machinery | Chennai +44 other locat...

In [77]:
final.shape

(600, 4)