In [2]:
import pandas as pd
import requests

In [15]:
responce = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=2d8ec9467876942fdc0a81b0759712ee&language=en-US&page=1')

In [16]:
responce.json() # all the data as it is from URL

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 26.2518,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.713,
   'vote_count': 29309},
  {'adult': False,
   'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 25.1984,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.684,
   'vote_count': 22119},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 16.8688,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.57,
   'vote_count': 13372},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 10.9865,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.6,
   'vote_count': 16886},
  {'adult': False,
   'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 9.0105,
   'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 9557},
  {'adult': False,
   'backdrop_path': '/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 20.4829,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.534,
   'vote_count': 17680},
  {'adult': False,
   'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
   'genre_ids': [18, 28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 30.7333,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 34779},
  {'adult': False,
   'backdrop_path': '/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 9.8248,
   'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.513,
   'vote_count': 4521},
  {'adult': False,
   'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 14.0846,
   'poster_path': '/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.503,
   'vote_count': 18583},
  {'adult': False,
   'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 17.3534,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.496,
   'vote_count': 19762},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 18.2199,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 25710},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80, 35],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 17.6289,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 29334},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 26.8365,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.48,
   'vote_count': 12132},
  {'adult': False,
   'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 10.3766,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-22',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 9271},
  {'adult': False,
   'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 36.73,
   'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
   'release_date': '2014-11-05',
   'title': 'Interstellar',
   'video': False,
   'vote_average': 8.463,
   'vote_count': 38336},
  {'adult': False,
   'backdrop_path': '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 16.185,
   'poster_path': '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 28901},
  {'adult': False,
   'backdrop_path': '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 13.828,
   'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.453,
   'vote_count': 13810},
  {'adult': False,
   'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
   'genre_ids': [28, 18],
   'id': 346,
   'original_language': 'ja',
   'original_title': '七人の侍',
   'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
   'popularity': 5.9117,
   'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
   'release_date': '1954-04-26',
   'title': 'Seven Samurai',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 4037},
  {'adult': False,
   'backdrop_path': '/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg',
   'genre_ids': [16, 18, 10752],
   'id': 12477,
   'original_language': 'ja',
   'original_title': '火垂るの墓',
   'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
   'popularity': 0.0073,
   'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
   'release_date': '1988-04-16',
   'title': 'Grave of the Fireflies',
   'video': False,
   'vote_average': 8.446,
   'vote_count': 6213},
  {'adult': False,
   'backdrop_path': '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg',
   'genre_ids': [35, 18],
   'id': 637,
   'original_language': 'it',
   'original_title': 'La vita è bella',
   'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
   'popularity': 13.9834,
   'poster_path': '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg',
   'release_date': '1997-12-20',
   'title': 'Life Is Beautiful',
   'video': False,
   'vote_average': 8.44,
   'vote_count': 13655}],
 'total_pages': 526,
 'total_results': 10507}

In [17]:
responce.json()['results']# only get dictionaries present in the List

[{'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 26.2518,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'title': 'The Shawshank Redemption',
  'video': False,
  'vote_average': 8.713,
  'vote_count': 29309},
 {'adult': False,
  'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 25.1984,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'title': 'The Godfather',
  'video': False,
  'vote_average': 8.684,
  'vote_count': 22119},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 16.8688,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'title': 'The Godfather Part II',
  'video': False,
  'vote_average': 8.57,
  'vote_count': 13372},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 10.9865,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'title': "Schindler's List",
  'video': False,
  'vote_average': 8.6,
  'vote_count': 16886},
 {'adult': False,
  'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
  'genre_ids': [18],
  'id': 389,
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 9.0105,
  'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
  'release_date': '1957-04-10',
  'title': '12 Angry Men',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 9557},
 {'adult': False,
  'backdrop_path': '/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 20.4829,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'title': 'Spirited Away',
  'video': False,
  'vote_average': 8.534,
  'vote_count': 17680},
 {'adult': False,
  'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
  'genre_ids': [18, 28, 80, 53],
  'id': 155,
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 30.7333,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'title': 'The Dark Knight',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 34779},
 {'adult': False,
  'backdrop_path': '/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 9.8248,
  'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
  'release_date': '1995-10-20',
  'title': 'Dilwale Dulhania Le Jayenge',
  'video': False,
  'vote_average': 8.513,
  'vote_count': 4521},
 {'adult': False,
  'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 14.0846,
  'poster_path': '/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg',
  'release_date': '1999-12-10',
  'title': 'The Green Mile',
  'video': False,
  'vote_average': 8.503,
  'vote_count': 18583},
 {'adult': False,
  'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 17.3534,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'title': 'Parasite',
  'video': False,
  'vote_average': 8.496,
  'vote_count': 19762},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 18.2199,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'title': 'The Lord of the Rings: The Return of the King',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 25710},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80, 35],
  'id': 680,
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 17.6289,
  'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  'release_date': '1994-09-10',
  'title': 'Pulp Fiction',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 29334},
 {'adult': False,
  'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 26.8365,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-08-26',
  'title': 'Your Name.',
  'video': False,
  'vote_average': 8.48,
  'vote_count': 12132},
 {'adult': False,
  'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
  'genre_ids': [37],
  'id': 429,
  'original_language': 'it',
  'original_title': 'Il buono, il brutto, il cattivo',
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
  'popularity': 10.3766,
  'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
  'release_date': '1966-12-22',
  'title': 'The Good, the Bad and the Ugly',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 9271},
 {'adult': False,
  'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
  'genre_ids': [12, 18, 878],
  'id': 157336,
  'original_language': 'en',
  'original_title': 'Interstellar',
  'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  'popularity': 36.73,
  'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  'release_date': '2014-11-05',
  'title': 'Interstellar',
  'video': False,
  'vote_average': 8.463,
  'vote_count': 38336},
 {'adult': False,
  'backdrop_path': '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 13,
  'original_language': 'en',
  'original_title': 'Forrest Gump',
  'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
  'popularity': 16.185,
  'poster_path': '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
  'release_date': '1994-06-23',
  'title': 'Forrest Gump',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 28901},
 {'adult': False,
  'backdrop_path': '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg',
  'genre_ids': [18, 80],
  'id': 769,
  'original_language': 'en',
  'original_title': 'GoodFellas',
  'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
  'popularity': 13.828,
  'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
  'release_date': '1990-09-12',
  'title': 'GoodFellas',
  'video': False,
  'vote_average': 8.453,
  'vote_count': 13810},
 {'adult': False,
  'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
  'genre_ids': [28, 18],
  'id': 346,
  'original_language': 'ja',
  'original_title': '七人の侍',
  'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
  'popularity': 5.9117,
  'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
  'release_date': '1954-04-26',
  'title': 'Seven Samurai',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 4037},
 {'adult': False,
  'backdrop_path': '/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg',
  'genre_ids': [16, 18, 10752],
  'id': 12477,
  'original_language': 'ja',
  'original_title': '火垂るの墓',
  'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
  'popularity': 0.0073,
  'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
  'release_date': '1988-04-16',
  'title': 'Grave of the Fireflies',
  'video': False,
  'vote_average': 8.446,
  'vote_count': 6213},
 {'adult': False,
  'backdrop_path': '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg',
  'genre_ids': [35, 18],
  'id': 637,
  'original_language': 'it',
  'original_title': 'La vita è bella',
  'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
  'popularity': 13.9834,
  'poster_path': '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg',
  'release_date': '1997-12-20',
  'title': 'Life Is Beautiful',
  'video': False,
  'vote_average': 8.44,
  'vote_count': 13655}]

In [18]:
pd.DataFrame(responce.json()['results'])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,26.2518,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.713,29309
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",25.1984,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.684,22119
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,16.8688,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.570,13372
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,10.9865,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.600,16886
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,9.0105,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.500,9557
5,False,/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",20.4829,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.534,17680
6,False,/dqK9Hag1054tghRQSqLSfrkvQnA.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,30.7333,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.500,34779
7,False,/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",9.8248,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.513,4521
8,False,/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,14.0846,/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg,1999-12-10,The Green Mile,False,8.503,18583
9,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",17.3534,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.496,19762
10,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,18.2199,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,The Lord of the Rings: The Return of the King,False,8.500,25710
11,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80, 35]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",17.6289,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,Pulp Fiction,False,8.500,29334
12,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,26.8365,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.480,12132
13,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,10.3766,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.500,9271
14,False,/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,36.7300,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,Interstellar,False,8.463,38336
15,False,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,16.1850,/saHP97rTPS5eLmrLQEcANmKrsFl.jpg,1994-06-23,Forrest Gump,False,8.500,28901
16,False,/gILte6Zd7m1YneIr6MVhh30S9pr.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",13.8280,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.453,13810
17,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,5.9117,/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg,1954-04-26,Seven Samurai,False,8.500,4037
18,False,/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.0073,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.446,6213
19,False,/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg,"[35, 18]",637,it,La vita è bella,A touching story of an Italian book seller of ...,13.9834,/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg,1997-12-20,Life Is Beautiful,False,8.440,13655

In [19]:
temp_df  =  pd.DataFrame(responce.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [20]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,26.2518,8.713,29309
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,25.1984,8.684,22119
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,16.8688,8.570,13372
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,10.9865,8.600,16886
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,9.0105,8.500,9557

In [21]:
df = pd.DataFrame() # create empty DataFrame
df

Empty DataFrame
Columns: []
Index: []

In [26]:
for i in range(1,526):
    responce = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=2d8ec9467876942fdc0a81b0759712ee&language=en-US&page={}'.format(i))
    # use .format(i) to collect all the dataset
    temp_df = pd.DataFrame(responce.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index = True) # ignore_index for continues indexing

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [28]:
import requests
import pandas as pd
import time
import warnings

# Use a list to store DataFrames, as appending to a DataFrame in a loop is inefficient
all_movie_data = [] 

# Configuration variables
API_KEY = '2d8ec9467876942fdc0a81b0759712ee'
BASE_URL = f'https://api.themoviedb.org/3/movie/top_rated?api_key={API_KEY}&language=en-US&page={{}}'
MAX_RETRIES = 3
SLEEP_TIME = 0.5 # Delay to avoid rate-limiting

# Loop from page 1 up to, but not including, page 526
for i in range(1, 526):
    print(f"Fetching page {i}...")
    
    # Retry mechanism for handling connection issues (like ConnectionResetError)
    for attempt in range(MAX_RETRIES):
        try:
            url = BASE_URL.format(i)
            # Add a timeout to prevent hanging connections
            response = requests.get(url, timeout=10) 
            # Raise an exception for bad status codes (4xx or 5xx)
            response.raise_for_status() 
            
            # Extract data safely
            results = response.json().get('results', [])
            if results:
                # Process the data into a temporary DataFrame
                temp_df = pd.DataFrame(results)[['id','title','overview','release_date','popularity','vote_average','vote_count']]
                # Add the temporary DataFrame to the list
                all_movie_data.append(temp_df)
                
            break # Success! Exit the retry loop
            
        except requests.exceptions.RequestException as e:
            # Handle error
            print(f"Error fetching page {i} on attempt {attempt + 1}: {e}")
            if attempt < MAX_RETRIES - 1:
                # Wait longer on subsequent failures
                delay = SLEEP_TIME * 2 ** attempt
                print(f"Waiting for {delay:.2f} seconds before retrying...")
                time.sleep(delay)
            else:
                print(f"Failed to fetch page {i} after {MAX_RETRIES} attempts. Skipping this page.")
    
    # Mandatory delay between requests to respect API rate limits
    time.sleep(SLEEP_TIME)

# After the loop finishes, efficiently combine all DataFrames into the final result
if all_movie_data:
    final_df = pd.concat(all_movie_data, ignore_index=True)
    print("\nData collection complete.")
    print(f"Total movies collected: {len(final_df)}")
else:
    print("\nNo data collected.")

Fetching page 1...
Fetching page 2...
Fetching page 3...
Fetching page 4...
Fetching page 5...
Fetching page 6...
Fetching page 7...
Fetching page 8...
Fetching page 9...
Fetching page 10...
Fetching page 11...
Fetching page 12...
Fetching page 13...
Fetching page 14...
Fetching page 15...
Fetching page 16...
Fetching page 17...
Fetching page 18...
Fetching page 19...
Fetching page 20...
Fetching page 21...
Fetching page 22...
Fetching page 23...
Fetching page 24...
Fetching page 25...
Fetching page 26...
Fetching page 27...
Fetching page 28...
Fetching page 29...
Fetching page 30...
Fetching page 31...
Fetching page 32...
Fetching page 33...
Fetching page 34...
Fetching page 35...
Fetching page 36...
Fetching page 37...
Fetching page 38...
Fetching page 39...
Fetching page 40...
Fetching page 41...
Fetching page 42...
Fetching page 43...
Fetching page 44...
Fetching page 45...
Fetching page 46...
Fetching page 47...
Fetching page 48...
Fetching page 49...
Error fetching page 49 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 49 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 50...
Error fetching page 50 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 51...
Error fetching page 51 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 51 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Error fetching page 51 on attempt 3: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Failed to fetch page 51 after 3 attempts. Skipping this page.
Fetching page 52...
Fetching page 53...
Fetching page 54...
Error fetching page 54 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 54 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 55...
Fetching page 56...
Fetching page 57...
Error fetching page 57 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 57 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Error fetching page 57 on attempt 3: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Failed to fetch page 57 after 3 attempts. Skipping this page.
Fetching page 58...
Error fetching page 58 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 59...
Error fetching page 59 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 59 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Error fetching page 59 on attempt 3: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Failed to fetch page 59 after 3 attempts. Skipping this page.
Fetching page 60...
Fetching page 61...
Fetching page 62...
Fetching page 63...
Error fetching page 63 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 63 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 64...
Fetching page 65...
Fetching page 66...
Error fetching page 66 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 66 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Error fetching page 66 on attempt 3: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Failed to fetch page 66 after 3 attempts. Skipping this page.
Fetching page 67...
Error fetching page 67 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 68...
Fetching page 69...
Error fetching page 69 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 69 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 70...
Fetching page 71...
Fetching page 72...
Error fetching page 72 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 73...
Error fetching page 73 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 73 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 74...
Error fetching page 74 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 74 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 75...
Fetching page 76...
Fetching page 77...
Fetching page 78...
Error fetching page 78 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 78 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 79...
Fetching page 80...
Fetching page 81...
Fetching page 82...
Fetching page 83...
Fetching page 84...
Fetching page 85...
Fetching page 86...
Fetching page 87...
Fetching page 88...
Fetching page 89...
Fetching page 90...
Fetching page 91...
Fetching page 92...
Fetching page 93...
Fetching page 94...
Fetching page 95...
Fetching page 96...
Fetching page 97...
Fetching page 98...
Fetching page 99...
Fetching page 100...
Fetching page 101...
Fetching page 102...
Fetching page 103...
Fetching page 104...
Fetching page 105...
Fetching page 106...
Fetching page 107...
Fetching page 108...
Fetching page 109...
Fetching page 110...
Fetching page 111...
Fetching page 112...
Fetching page 113...
Fetching page 114...
Fetching page 115...
Fetching page 116...
Fetching page 117...
Fetching page 118...
Fetching page 119...
Fetching page 120...
Fetching page 121...
Fetching page 122...
Fetching page 123...
Fetching page 124...
Fetching page 125...
Fetching page 126...
Fetching page 127...
Fetching page 128...
Fetching page 129...
Fetching page 130...
Fetching page 131...
Fetching page 132...
Fetching page 133...
Fetching page 134...
Fetching page 135...
Fetching page 136...
Fetching page 137...
Fetching page 138...
Fetching page 139...
Fetching page 140...
Fetching page 141...
Fetching page 142...
Fetching page 143...
Fetching page 144...
Fetching page 145...
Fetching page 146...
Fetching page 147...
Fetching page 148...
Fetching page 149...
Fetching page 150...
Fetching page 151...
Fetching page 152...
Fetching page 153...
Fetching page 154...
Fetching page 155...
Fetching page 156...
Fetching page 157...
Fetching page 158...
Fetching page 159...
Fetching page 160...
Fetching page 161...
Fetching page 162...
Fetching page 163...
Fetching page 164...
Fetching page 165...
Fetching page 166...
Fetching page 167...
Fetching page 168...
Fetching page 169...
Fetching page 170...
Fetching page 171...
Fetching page 172...
Fetching page 173...
Fetching page 174...
Fetching page 175...
Fetching page 176...
Fetching page 177...
Fetching page 178...
Fetching page 179...
Fetching page 180...
Fetching page 181...
Fetching page 182...
Fetching page 183...
Fetching page 184...
Fetching page 185...
Fetching page 186...
Fetching page 187...
Fetching page 188...
Fetching page 189...
Fetching page 190...
Fetching page 191...
Fetching page 192...
Fetching page 193...
Fetching page 194...
Fetching page 195...
Fetching page 196...
Fetching page 197...
Fetching page 198...
Fetching page 199...
Fetching page 200...
Fetching page 201...
Fetching page 202...
Fetching page 203...
Fetching page 204...
Fetching page 205...
Fetching page 206...
Fetching page 207...
Fetching page 208...
Fetching page 209...
Fetching page 210...
Fetching page 211...
Fetching page 212...
Fetching page 213...
Fetching page 214...
Fetching page 215...
Fetching page 216...
Fetching page 217...
Fetching page 218...
Fetching page 219...
Fetching page 220...
Fetching page 221...
Fetching page 222...
Fetching page 223...
Fetching page 224...
Fetching page 225...
Fetching page 226...
Fetching page 227...
Fetching page 228...
Error fetching page 228 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 229...
Fetching page 230...
Error fetching page 230 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 231...
Fetching page 232...
Error fetching page 232 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 232 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Error fetching page 232 on attempt 3: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Failed to fetch page 232 after 3 attempts. Skipping this page.
Fetching page 233...
Error fetching page 233 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 233 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 234...
Fetching page 235...
Error fetching page 235 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 236...
Fetching page 237...
Error fetching page 237 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 238...
Fetching page 239...
Error fetching page 239 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 239 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 240...
Error fetching page 240 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 240 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 241...
Fetching page 242...
Fetching page 243...
Error fetching page 243 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 244...
Error fetching page 244 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 244 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 245...
Fetching page 246...
Fetching page 247...
Fetching page 248...
Error fetching page 248 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 249...
Error fetching page 249 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 249 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 250...
Error fetching page 250 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 250 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 251...
Fetching page 252...
Fetching page 253...
Error fetching page 253 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 254...
Error fetching page 254 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 255...
Fetching page 256...
Error fetching page 256 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 257...
Fetching page 258...
Error fetching page 258 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 258 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 259...
Error fetching page 259 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 259 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 260...
Fetching page 261...
Error fetching page 261 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 261 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 262...
Error fetching page 262 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 263...
Fetching page 264...
Error fetching page 264 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 265...
Fetching page 266...
Error fetching page 266 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Error fetching page 266 on attempt 2: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 1.00 seconds before retrying...
Fetching page 267...
Fetching page 268...
Fetching page 269...
Fetching page 270...
Fetching page 271...
Fetching page 272...
Error fetching page 272 on attempt 1: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Waiting for 0.50 seconds before retrying...
Fetching page 273...

In [27]:
df.to_csv('movies.csv)

SyntaxError: EOL while scanning string literal (2956738324.py, line 1)