In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv("cars.csv")
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [17]:
# df['brand'].value_counts()

# Unique Brands 
df['brand'].nunique()

32

In [18]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [19]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# 1. One Hot Encoding Using Pandas

In [20]:
pd.get_dummies(df,columns = ['fuel','owner'])

# it will create new columns for every attribute present in the Fuel and Owner cols
# Before shape -->  5 
# After Shape -->  [3 original  , 4 from Fuel , 5 from Owner ]  -->  12 cols

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [21]:


aa = pd.get_dummies(df,columns = ['fuel','owner'])
aa.shape

(8128, 12)

# 2. K - 1 One Hot Encoding / Dummy Variable Trap

## remove 1st Column

In [22]:
 pd.get_dummies(df,columns = ['fuel','owner'],drop_first = True)

## Here we get 10 Columns because it removes 1 - 1 column from each category

### It will don't remember which columns are droped

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# 3. OneHotEncoding Using Sklearn

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,:-1], test_size = 0.2, random_state = 0)

In [24]:
df   # still our data is same

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [25]:
X_train.head()

# iloc not take last value   iloc[:,0:4] --> 0 to 3

         brand  km_driven    fuel         owner
3042   Hyundai      60000     LPG   First Owner
1520      Tata     150000  Diesel   Third Owner
2611   Hyundai     110000  Diesel  Second Owner
3544  Mahindra      28000  Diesel  Second Owner
4138    Maruti      15000  Petrol   First Owner

In [26]:
X_test.head()

         brand  km_driven    fuel        owner
3558   Hyundai      40000  Diesel  First Owner
233   Mahindra      70000  Diesel  First Owner
7952    Maruti       5000  Petrol  First Owner
572     Maruti     120000  Petrol  Third Owner
6960     Lexus      20000  Petrol  First Owner

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [40]:
# ohe = OneHotEncoder()
## Without dropping First Columns

ohe = OneHotEncoder(drop = 'first')
# it will drop first columns of both categories

##  Only taking 'fuel','owner' columns for One Hot Encoding

In [41]:
ohe.fit_transform(X_train[['fuel','owner']])   

#doing both (fit, transform) at once
# by default it creates sparse matrix
# 6502 x 9 --> It created 9 columns -- 4 from Fuel , 5 from Owner --

<6502x7 sparse matrix of type '<class 'numpy.float64'>'
	with 8735 stored elements in Compressed Sparse Row format>

In [42]:
ohe.fit_transform(X_train[['fuel','owner']]).toarray()

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [43]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [44]:
X_test_new = ohe.transform(X_train[['fuel','owner']]).toarray()

##  Now concatenate brand , km_driven columns to new data

In [45]:
X_train[['brand','km_driven']].values

array([['Hyundai', 60000],
       ['Tata', 150000],
       ['Hyundai', 110000],
       ...,
       ['Hyundai', 90000],
       ['Volkswagen', 90000],
       ['Hyundai', 110000]], dtype=object)

In [46]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new))

array([['Hyundai', 60000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 150000, 1.0, ..., 0.0, 0.0, 1.0],
       ['Hyundai', 110000, 1.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Hyundai', 90000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Volkswagen', 90000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 110000, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [48]:
X_train_new.shape

(6502, 7)

In [47]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new)).shape

(6502, 9)

In [52]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop = 'first', dtype = np.int32)   
## we can control datatypes also --> float convert to Integer

ohe.fit_transform(X_train[['fuel','owner']])   
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_train_new.shape

(6502, 7)

# 4. One Hot Encoding With Top Categories

In [58]:
counts = df['brand'].value_counts()

In [59]:
df['brand'].nunique()
threshold = 100

In [61]:
repl = counts[counts <= threshold].index

# if threshold is lessthan 100 we store in repl

In [65]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample

<bound method NDFrame.sample of         BMW  Chevrolet   Ford  Honda  Hyundai  Mahindra  Maruti  Renault  \
0     False      False  False  False    False     False    True    False
1     False      False  False  False    False     False   False    False
2     False      False  False   True    False     False   False    False
3     False      False  False  False     True     False   False    False
4     False      False  False  False    False     False    True    False
...     ...        ...    ...    ...      ...       ...     ...      ...
8123  False      False  False  False     True     False   False    False
8124  False      False  False  False     True     False   False    False
8125  False      False  False  False    False     False    True    False
8126  False      False  False  False    False     False   False    False
8127  False      False  False  False    False     False   False    False

      Skoda   Tata  Toyota  Volkswagen  uncommon
0     False  False   False       False     False
1      True  False   False       False     False
2     False  False   False       False     False
3     False  False   False       False     False
4     False  False   False       False     False
...     ...    ...     ...         ...       ...
8123  False  False   False       False     False
8124  False  False   False       False     False
8125  False  False   False       False     False
8126  False   True   False       False     False
8127  False   True   False       False     False

[8128 rows x 13 columns]>