<a href="https://colab.research.google.com/github/SANGRAMLEMBE/100_days_of_ML/blob/main/Day45_Feature_Construction/Feature_Construction_Splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [3]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch',"Survived"]]

In [4]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [5]:
df.dropna(inplace = True)

In [6]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [9]:
X= df.iloc[:,0:4]
y = df.iloc[:,-1]

In [11]:
np.mean(cross_val_score(LogisticRegression(),X ,y,scoring = 'accuracy', cv = 20))

np.float64(0.6933333333333332)

# Feature Construction

In [12]:
X['Family_size']  = X['SibSp']  + X['Parch'] + 1

In [13]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [14]:
def myfunc(num):
  if num == 1:
    #alone
    return 0
  elif num>1 and num<=4:
    # small family
    return 1
  else:
    # Large Family
    return 2

In [16]:
myfunc(5)

2

In [17]:
X['Family_type']  = X['Family_size'].apply(myfunc)

In [18]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [19]:
X.drop(columns=['SibSp','Parch','Family_size'], inplace = True)

In [20]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [22]:
np.mean(cross_val_score(LogisticRegression(),X ,y,scoring = 'accuracy', cv = 20))

np.float64(0.7003174603174602)

#Feature Splitting

In [23]:
df = pd.read_csv('train.csv')

In [24]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [27]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [28]:
df['Name'].str.split(',',expand = True)

# It will split last name and first name by ,

             0                                            1
0       Braund                              Mr. Owen Harris
1      Cumings   Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                  Miss. Laina
3     Futrelle           Mrs. Jacques Heath (Lily May Peel)
4        Allen                            Mr. William Henry
..         ...                                          ...
886   Montvila                                  Rev. Juozas
887     Graham                         Miss. Margaret Edith
888   Johnston               Miss. Catherine Helen "Carrie"
889       Behr                              Mr. Karl Howell
890     Dooley                                  Mr. Patrick

[891 rows x 2 columns]

In [30]:
df['Name'].str.split(',',expand = True)[1].str.split('.',expand = True)

         0                                       1     2
0       Mr                             Owen Harris  None
1      Mrs   John Bradley (Florence Briggs Thayer)  None
2     Miss                                   Laina  None
3      Mrs           Jacques Heath (Lily May Peel)  None
4       Mr                           William Henry  None
..     ...                                     ...   ...
886    Rev                                  Juozas  None
887   Miss                          Margaret Edith  None
888   Miss                Catherine Helen "Carrie"  None
889     Mr                             Karl Howell  None
890     Mr                                 Patrick  None

[891 rows x 3 columns]

In [32]:
df['Title'] = df['Name'].str.split(',',expand = True)[1].str.split('.',expand = True)[0]

In [33]:
df[['Title', 'Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [35]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64